// Top-level build file for V2RayEZ Universal Core Android wrapper
// Produces .apk with multi-ABI support (arm64-v8a, armeabi-v7a, x86_64)

plugins {
    id 'com.android.application' version '8.7.3' apply false
    id 'org.jetbrains.kotlin.android' version '1.9.22' apply false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
