import {currentLanguage,setLanguage,t} from './i18n.js';
const tauri=window.__TAURI__||{core:{invoke:async c=>c==='load_settings'?{}:c==='connection_state'?{state:'disconnected',elapsed:0}:c==='installed_applications'?[]:c==='traffic_totals'?{uploaded:0,downloaded:0}:c==='vpn_probe'?{ping:null,location:''}:c==='activate_license'||c==='validate_license'?{allowed:false,result:'DENIED',reason:'desktop backend unavailable',redactedSerial:'',deviceIdPreview:'browser'}:c==='clear_license'?{allowed:false,result:'DENIED',reason:'serial_cleared',redactedSerial:'',deviceIdPreview:'browser'}:c==='test_ai_provider'?{success:true,providerName:'V2RayEZ Local AI',source:'local_fallback',text:'Local fallback ready'}:undefined},event:{listen:async()=>()=>{}},opener:{openUrl:async()=>{}},dialog:{open:async()=>null}};
const {invoke}=tauri.core,{listen}=tauri.event,openUrl=tauri.opener?.openUrl||tauri.opener?.open,$=id=>document.getElementById(id);
const defaults={automaticUpdates:true,language:'en',appearance:'dark',connectionMode:'vpn',routingMode:'bypass-local',dnsLeakProtection:true,ipv6Behavior:'tunnel',killSwitch:false,splitApplications:[],routeExclusions:[],protocol:'gool',scanMode:'turbo',logLevel:'info',ipMode:'v4',obfuscation:'balanced',masqueTransport:'h3',socksAddress:'127.0.0.1:1819',allowRemoteListener:false,peer:'',wgKeepalive:5,stallTimeout:90,watchdog:true,configPath:'',wgConfigPath:'',masqueConfigPath:'',quickReconnect:true,license:{validationUrl:'',accountId:'',deviceLabel:'',allowOfflineGrace:true,lastResult:'not_validated',lastReason:'',expiresAt:'',offlineGraceUntil:''},aiEngine:{enabled:true,selectedProviderId:'local-aether',autoFallbackToLocal:true,localModel:'aether-anti-dpi-local',providers:[{id:'local-aether',name:'V2RayEZ Local AI',providerType:'local',enabled:true,baseUrl:'local://aether',endpoint:'',model:'aether-anti-dpi-local',apiKeyAlias:'',headersJson:'{}',requestTemplate:'',responsePath:'text',timeoutMs:30000}],lastProviderTestResult:'not_tested'}};
let settings={...defaults},state='disconnected',trafficTimer,pingTimer,reconnectTimer,reconnectAttempts=0,desiredConnected=false,operation=null,operationVersion=0,apps=[],selected=new Set();
function selectSegment(id,value){$(id)?.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.value===value))}
function segmentValue(id){return $(id)?.querySelector('.active')?.dataset.value}
function setOptions(el,values,selectedValue){el.replaceChildren(...values.map(([value,label])=>{const o=document.createElement('option');o.value=value;o.textContent=label;o.selected=value===selectedValue;return o}))}
function formatNumber(value){return new Intl.NumberFormat(currentLanguage(),{minimumFractionDigits:1,maximumFractionDigits:1}).format(value)}
function formatBytes(value){if(!Number.isFinite(value)||value<0)return'--';if(value<1048576)return formatNumber(value/1024)+' KB';if(value<1073741824)return formatNumber(value/1048576)+' MB';return formatNumber(value/1073741824)+' GB'}
function renderOptions(){setOptions($('scanMode'),[['turbo','Turbo'],['balanced','Balanced'],['thorough','Thorough'],['stealth','Stealth'],['ironclad','Ironclad']],settings.scanMode);syncProtocol()}
function syncProtocol(){settings.protocol=segmentValue('protocol')||settings.protocol;$('transportField').classList.toggle('hidden',settings.protocol!=='masque')}
function updateSelectedCount(){$('selectedCount').textContent=new Intl.NumberFormat(currentLanguage()).format(selected.size)+' '+t('picker.selected')}
function syncSplit(){const on=$('splitEnabled').checked;$('splitControls').classList.toggle('hidden',!on);settings.routingMode=on?(segmentValue('splitMode')||'split-include'):'bypass-local';updateSelectedCount()}
function licenseFromUi(){return{...(settings.license||defaults.license),validationUrl:$('licenseValidationUrl').value.trim(),accountId:$('licenseAccount').value.trim(),deviceLabel:$('licenseDeviceLabel').value.trim(),allowOfflineGrace:$('licenseOfflineGrace').checked}}
function currentAiProviderFromUi(){const id=($('aiProviderId').value||$('aiProviderList').value||settings.aiEngine?.selectedProviderId||'local-aether').trim()||'local-aether';return{id,name:$('aiProviderName').value.trim()||'Custom AI provider',providerType:$('aiProviderType').value,enabled:true,baseUrl:$('aiBaseUrl').value.trim(),endpoint:$('aiEndpoint').value.trim(),model:$('aiModel').value.trim(),apiKeyAlias:$('aiApiAlias').value.trim(),headersJson:$('aiHeaders').value.trim()||'{}',requestTemplate:$('aiTemplate').value,responsePath:$('aiResponsePath').value.trim(),timeoutMs:30000}}
function aiFromUi(){const current=settings.aiEngine||defaults.aiEngine,provider=currentAiProviderFromUi(),providers=(current.providers||[]).filter(p=>p.id!==provider.id);return{...current,enabled:$('aiEnabled').checked,autoFallbackToLocal:$('aiFallback').checked,selectedProviderId:provider.id,providers:[...providers,provider]}}
function readSettings(){return{...settings,language:currentLanguage(),appearance:$('appearance').value,automaticUpdates:$('automaticUpdates').checked,connectionMode:segmentValue('connectionMode'),routingMode:settings.routingMode,protocol:segmentValue('protocol'),masqueTransport:segmentValue('transport')||settings.masqueTransport,scanMode:$('scanMode').value,dnsLeakProtection:$('dnsLeakProtection').checked,killSwitch:$('killSwitch').checked,quickReconnect:$('quickReconnect').checked,peer:$('peer').value.trim(),splitApplications:[...selected],license:licenseFromUi(),aiEngine:aiFromUi()}}
function queueSave(){settings=readSettings();clearTimeout(queueSave.timer);queueSave.timer=setTimeout(()=>invoke('save_settings',{settings}).catch(showError),250)}
function renderLicenseStatus(status){const allowed=!!status?.allowed,reason=status?.reason||settings.license?.lastReason||t('license.statusEmpty'),serial=status?.redactedSerial||'';$('licenseStatus').textContent=(allowed?t('license.allowed'):t('license.denied'))+' · '+reason+(serial?' · '+serial:'')}
function selectedProvider(){const engine=settings.aiEngine||defaults.aiEngine;return(engine.providers||defaults.aiEngine.providers).find(p=>p.id===engine.selectedProviderId)||(engine.providers||defaults.aiEngine.providers)[0]||defaults.aiEngine.providers[0]}
function renderAiProvider(){const engine=settings.aiEngine||defaults.aiEngine,providers=engine.providers?.length?engine.providers:defaults.aiEngine.providers;setOptions($('aiProviderList'),providers.map(p=>[p.id,p.name||p.id]),engine.selectedProviderId);const p=selectedProvider();$('aiEnabled').checked=engine.enabled;$('aiFallback').checked=engine.autoFallbackToLocal;$('aiProviderId').value=p.id||'';$('aiProviderName').value=p.name||'';$('aiProviderType').value=p.providerType||'generic';$('aiBaseUrl').value=p.baseUrl||'';$('aiEndpoint').value=p.endpoint||'';$('aiModel').value=p.model||'';$('aiApiAlias').value=p.apiKeyAlias||'';$('aiSecret').value='';$('aiHeaders').value=p.headersJson||'{}';$('aiTemplate').value=p.requestTemplate||'';$('aiResponsePath').value=p.responsePath||'';$('aiStatus').textContent=engine.lastProviderTestResult||t('ai.statusEmpty')}
function renderSettings(saved){settings={...defaults,...saved,license:{...defaults.license,...(saved?.license||{})},aiEngine:{...defaults.aiEngine,...(saved?.aiEngine||{}),providers:saved?.aiEngine?.providers?.length?saved.aiEngine.providers:defaults.aiEngine.providers}};setLanguage(settings.language);selectSegment('connectionMode',settings.connectionMode);selectSegment('protocol',settings.protocol);selectSegment('transport',settings.masqueTransport);selectSegment('splitMode',settings.routingMode==='split-exclude'?'split-exclude':'split-include');selected=new Set(settings.splitApplications||[]);$('splitEnabled').checked=['split-include','split-exclude'].includes(settings.routingMode);$('peer').value=settings.peer||'';$('dnsLeakProtection').checked=settings.dnsLeakProtection;$('killSwitch').checked=settings.killSwitch;$('quickReconnect').checked=settings.quickReconnect;$('automaticUpdates').checked=settings.automaticUpdates;$('appearance').value=settings.appearance;$('language').value=settings.language;$('licenseValidationUrl').value=settings.license.validationUrl||'';$('licenseAccount').value=settings.license.accountId||'';$('licenseDeviceLabel').value=settings.license.deviceLabel||'';$('licenseOfflineGrace').checked=settings.license.allowOfflineGrace!==false;renderLicenseStatus({allowed:settings.license.lastResult==='ALLOWED',reason:settings.license.lastReason});renderAiProvider();document.body.dataset.theme=settings.appearance;renderOptions();syncSplit();$('currentVersion').textContent='2.0.0'}
function openDrawer(){$('drawer').classList.add('open');$('drawerScrim').classList.add('open')}
function closeDrawer(){$('drawer').classList.remove('open');$('drawerScrim').classList.remove('open')}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+name));document.querySelectorAll('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$('pageTitle').textContent=name==='connect'?'V2RayEZ':t('nav.'+name);closeDrawer();window.scrollTo({top:0,behavior:'instant'})}
function setState(next){state=next;const active=!['disconnected','error'].includes(next);$('connectionOrb').className='connection-orb '+next;$('statusPill').className='status-pill '+next;$('orbLabel').textContent=next==='connected'?t('actions.disconnect'):next==='disconnecting'?t('status.disconnecting'):active?t('status.connecting'):t('actions.connect');$('statusTitle').textContent=t('status.'+next);const key=next==='connected'?'connected':next==='reconnecting'?'reconnecting':next==='disconnecting'?'disconnecting':next==='disconnected'?'ready':next==='scanning'||next==='connecting'?'connecting':'error';$('statusMessage')?.replaceChildren(document.createTextNode(t('connection.'+key)));$('drawerState').textContent=t('status.'+next);if(next==='disconnected'||next==='error'){stopTelemetry();$('uploadTraffic').textContent='--';$('downloadTraffic').textContent='--';$('pingValue').textContent=t('traffic.ping')+': --';$('locationValue').textContent=t('traffic.locationUnavailable')}else if(next!=='connected'){$('locationValue').textContent=t('traffic.locationDetecting')}}
function showError(error){$('toast').textContent=typeof error==='string'?error:error?.message||String(error);$('toast').className='show error';setTimeout(()=>$('toast').className='',5000)}
function toast(message){$('toast').textContent=message;$('toast').className='show';setTimeout(()=>$('toast').className='',2600)}
async function connect(){if(operation||!['disconnected','error'].includes(state))return;const version=++operationVersion;operation='connect';desiredConnected=true;settings=readSettings();setState('connecting');try{await invoke('save_settings',{settings});if(version!==operationVersion)return;setState('scanning');await invoke('connect',{settings});if(version===operationVersion)reconnectAttempts=0}catch(error){if(version===operationVersion){setState('error');showError(error)}}finally{if(version===operationVersion)operation=null}}
async function disconnect(){if(operation==='disconnect'||state==='disconnecting'||state==='disconnected')return;const version=++operationVersion;operation='disconnect';desiredConnected=false;clearTimeout(reconnectTimer);reconnectTimer=null;stopTelemetry();setState('disconnecting');try{await invoke('disconnect')}catch(error){if(version===operationVersion)showError(error)}finally{if(version===operationVersion){operation=null;setState('disconnected')}}}
function scheduleReconnect(){if(!desiredConnected||!settings.quickReconnect||reconnectAttempts>=5||reconnectTimer||operation)return false;reconnectAttempts++;setState('reconnecting');reconnectTimer=setTimeout(async()=>{reconnectTimer=null;if(!desiredConnected||operation)return;const version=++operationVersion;operation='disconnect';try{await invoke('disconnect')}finally{if(version===operationVersion){operation=null;if(desiredConnected){setState('disconnected');connect()}}}},Math.min(20000,1500*2**(reconnectAttempts-1)));return true}
function stopTelemetry(){clearInterval(trafficTimer);clearInterval(pingTimer);trafficTimer=pingTimer=null}
function startTelemetry(){stopTelemetry();const traffic=async()=>{try{const m=await invoke('traffic_totals');$('uploadTraffic').textContent=formatBytes(m.uploaded);$('downloadTraffic').textContent=formatBytes(m.downloaded)}catch{}};const probe=async()=>{try{const m=await invoke('vpn_probe',{settings});if(m.ping!=null)$('pingValue').textContent=t('traffic.ping')+': '+new Intl.NumberFormat(currentLanguage()).format(m.ping)+' ms';if(m.location)$('locationValue').textContent=m.location}catch{}};traffic();probe();trafficTimer=setInterval(traffic,1000);pingTimer=setInterval(probe,15000)}
async function openTelegram(){try{await openUrl('tg://resolve?domain=v2rayez')}catch{try{await openUrl('https://t.me/v2rayez')}catch{toast(t('toast.telegram'))}}}
async function checkUpdates(manual=false){$('checkUpdates').disabled=true;if(manual)$('updateStatus').textContent=t('updates.checking');try{const info=await invoke('check_for_update');$('currentVersion').textContent=info.currentVersion||'2.0.0';$('updateBadge').classList.toggle('hidden',!info.available);if(info.available){$('updateStatus').textContent=t('updates.available');$('updateAction').classList.remove('hidden');$('updateAction').textContent=t('updates.download')}else if(manual){$('updateStatus').textContent=t('updates.upToDate');toast(t('toast.updated'))}}catch(error){if(manual){$('updateStatus').textContent=t('updates.failed');showError(error)}}finally{$('checkUpdates').disabled=false}}
async function updateAction(){try{if($('updateAction').textContent===t('updates.install')){await invoke('install_update');return}$('updateProgress').classList.remove('hidden');await invoke('download_update');$('updateAction').textContent=t('updates.install');$('updateStatus').textContent=t('updates.ready')}catch(error){showError(error)}}
function renderApps(){const query=$('appSearch').value.toLowerCase(),visible=apps.filter(a=>(a.name+' '+a.path).toLowerCase().includes(query));$('appList').replaceChildren(...visible.map(app=>{const row=document.createElement('div');row.className='app-row';row.innerHTML='<span class="app-icon">EXE</span><span><b></b><small></small></span><input type="checkbox">';if(app.icon){const image=document.createElement('img');image.className='app-icon';image.alt='';image.src='data:image/png;base64,'+app.icon;row.querySelector('.app-icon').replaceWith(image)}row.querySelector('b').textContent=app.name;row.querySelector('small').textContent=app.path;row.querySelector('input').checked=selected.has(app.path);row.onclick=e=>{if(e.target.tagName!=='INPUT')row.querySelector('input').checked=!row.querySelector('input').checked;row.querySelector('input').checked?selected.add(app.path):selected.delete(app.path);updateSelectedCount()};return row}))}
async function openApps(){try{apps=await invoke('installed_applications');for(const path of selected)if(!apps.some(a=>a.path===path))apps.push({name:path.split(/[\\/]/).pop(),path,icon:''});renderApps();$('appDialog').classList.remove('hidden')}catch(error){showError(error)}}
function closeApps(){$('appDialog').classList.add('hidden')}
async function activateLicense(){try{settings=readSettings();const result=await invoke('activate_license',{settings,licenseKey:$('licenseSerial').value.trim()});settings.license={...settings.license,lastResult:result.result,lastReason:result.reason,expiresAt:result.expiresAt||'',offlineGraceUntil:result.offlineGraceUntil||''};renderLicenseStatus(result);if(result.allowed)$('licenseSerial').value='';await invoke('save_settings',{settings})}catch(error){showError(error)}}
async function validateLicense(){try{settings=readSettings();const result=await invoke('validate_license',{settings});settings.license={...settings.license,lastResult:result.result,lastReason:result.reason,expiresAt:result.expiresAt||'',offlineGraceUntil:result.offlineGraceUntil||''};renderLicenseStatus(result);await invoke('save_settings',{settings})}catch(error){showError(error)}}
async function clearLicense(){try{const result=await invoke('clear_license');settings.license={...settings.license,lastResult:'not_validated',lastReason:result.reason||'serial_cleared',expiresAt:'',offlineGraceUntil:''};$('licenseSerial').value='';renderLicenseStatus(result);await invoke('save_settings',{settings})}catch(error){showError(error)}}
async function saveAiProvider(){try{settings=readSettings();const alias=$('aiApiAlias').value.trim(),secret=$('aiSecret').value;if(alias&&secret)await invoke('save_ai_secret',{alias,secret});$('aiSecret').value='';await invoke('save_settings',{settings});renderAiProvider();toast(t('ai.saveProvider'))}catch(error){showError(error)}}
async function testAiProvider(){try{settings=readSettings();const result=await invoke('test_ai_provider',{settings,providerId:settings.aiEngine.selectedProviderId,apiSecret:$('aiSecret').value.trim()||null});$('aiStatus').textContent=(result.success?'OK':'FAIL')+' · '+(result.providerName||'AI')+' · '+(result.source||'external')+(result.error?' · '+result.error:'');if(result.text)toast(result.text.slice(0,180))}catch(error){showError(error)}}
$('menuButton').onclick=openDrawer;$('drawerScrim').onclick=closeDrawer;$('telegramButton').onclick=openTelegram;document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('connectionOrb').onclick=()=>state==='disconnecting'?undefined:['connected','scanning','connecting','reconnecting'].includes(state)?disconnect():connect();
$('connectionMode').onclick=e=>{if(e.target.dataset.value){selectSegment('connectionMode',e.target.dataset.value);queueSave()}};$('protocol').onclick=e=>{if(e.target.dataset.value){selectSegment('protocol',e.target.dataset.value);syncProtocol();queueSave()}};$('transport').onclick=e=>{if(e.target.dataset.value){selectSegment('transport',e.target.dataset.value);queueSave()}};$('splitMode').onclick=e=>{if(e.target.dataset.value){selectSegment('splitMode',e.target.dataset.value);syncSplit();queueSave()}};$('splitEnabled').onchange=()=>{syncSplit();queueSave()};$('aiProviderList').onchange=()=>{settings.aiEngine={...(settings.aiEngine||defaults.aiEngine),selectedProviderId:$('aiProviderList').value};renderAiProvider()};
document.querySelectorAll('input,select').forEach(e=>e.addEventListener('change',()=>{if(e.id==='language'){settings.language=e.value;setLanguage(e.value);setState(state);updateSelectedCount()}if(e.id==='appearance')document.body.dataset.theme=e.value;queueSave()}));$('resetSettings').onclick=()=>{renderSettings(defaults);queueSave()};$('openApps').onclick=openApps;$('closeApps').onclick=closeApps;$('applyApps').onclick=()=>{closeApps();queueSave()};$('appSearch').oninput=renderApps;$('selectAll').onclick=()=>{apps.forEach(a=>selected.add(a.path));renderApps();updateSelectedCount()};$('clearAll').onclick=()=>{selected.clear();renderApps();updateSelectedCount()};
$('activateLicense').onclick=activateLicense;$('validateLicense').onclick=validateLicense;$('clearLicense').onclick=clearLicense;$('saveAiProvider').onclick=saveAiProvider;$('testAiProvider').onclick=testAiProvider;$('manageNotifications').onclick=()=>openUrl('ms-settings:notifications').catch(showError);$('addExecutable').onclick=async()=>{try{const path=await tauri.dialog.open({multiple:false,filters:[{name:'Executable',extensions:['exe']}]});if(path){selected.add(path);if(!apps.some(a=>a.path===path))apps.push({name:path.split(/[\\/]/).pop(),path,icon:''});renderApps();toast(t('picker.added'))}}catch(error){showError(error)}};$('checkUpdates').onclick=()=>checkUpdates(true);$('updateAction').onclick=updateAction;document.querySelectorAll('[data-external]').forEach(b=>b.onclick=()=>openUrl(b.dataset.external).catch(showError));
await listen('aether-log',e=>console.info('[Aether]',e.payload));await listen('aether-status',e=>{if(operation==='disconnect'&&e.payload.state!=='disconnected')return;if(!desiredConnected&&!['disconnected','error'].includes(e.payload.state))return;if(e.payload.state==='error'&&scheduleReconnect())return;setState(e.payload.state);if(e.payload.state==='connected')startTelemetry()});await listen('routing-status',e=>{if(operation==='disconnect'||!desiredConnected)return;if(e.payload.state==='reconnecting')setState('reconnecting');if(e.payload.state==='error'&&!scheduleReconnect())setState('error');if(e.payload.state==='connected'){reconnectAttempts=0;setState('connected');startTelemetry()}});await listen('update-progress',e=>{if(e.payload.percent!=null){$('updateProgress').classList.remove('hidden');$('updateProgress').value=e.payload.percent}});await listen('tray-connect',connect);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('appDialog').classList.contains('hidden'))closeApps();else closeDrawer()}if(e.key==='Backspace'&&!['INPUT','SELECT'].includes(document.activeElement.tagName)&&!$('view-connect').classList.contains('active'))showView('connect')});
try{renderSettings(await invoke('load_settings'))}catch{renderSettings(defaults)}try{const snapshot=await invoke('connection_state');desiredConnected=snapshot.state!=='disconnected';setState(snapshot.state);if(snapshot.state==='connected')startTelemetry()}catch{setState('disconnected')}if(settings.automaticUpdates)setTimeout(()=>checkUpdates(false),1200);setInterval(()=>{if(settings.automaticUpdates)checkUpdates(false)},12*60*60*1000);
