const en = {
  'brand.subtitle':'Private network','nav.connect':'Connect','nav.configurations':'Configurations','nav.settings':'Settings','nav.about':'About',
  'actions.connect':'CONNECT','actions.disconnect':'DISCONNECT','actions.reset':'Reset Defaults','actions.apply':'Apply','actions.selectAll':'Select All','actions.clearAll':'Clear All',
  'status.disconnected':'V2RayEZ Ready','status.connected':'V2RayEZ Active','status.connecting':'Connecting…','status.disconnecting':'Disconnecting…','status.scanning':'Scanning…','status.reconnecting':'Reconnecting…','status.error':'Connection error',
  'connection.ready':'','connection.connected':'','connection.connecting':'Preparing a secure route.','connection.disconnecting':'Restoring your network.','connection.reconnecting':'Recovering the secure route.','connection.error':'V2RayEZ needs attention.','connection.tap':'Tap to secure',
  'traffic.upload':'Upload Traffic','traffic.download':'Download Traffic','traffic.ping':'Ping','traffic.locationUnavailable':'Location unavailable','traffic.locationDetecting':'Detecting location…',
  'config.mode':'Connection Mode','config.vpn':'Device VPN','config.smart':'Smart Connect','config.proxy':'SOCKS5 Proxy','config.protocol':'Protocol','config.scan':'Scan Mode','config.transport':'MASQUE Transport','config.endpoint':'Custom Endpoint','config.reconnect':'Auto Reconnect','config.reconnectHelp':'Recover after temporary failures','config.dns':'Private DNS Routing','config.dnsHelp':'Route DNS through V2RayEZ','config.kill':'Fail Closed','config.killHelp':'Block traffic while recovering',
  'split.title':'Split Tunneling','split.help':'Choose which applications use V2RayEZ','split.include':'Include Apps','split.exclude':'Exclude Apps','split.select':'Select Applications','split.search':'Search applications','split.add':'Add Executable',
  'settings.appearance':'Appearance','settings.system':'System','settings.light':'Light','settings.dark':'Dark','settings.language':'Language','settings.notifications':'Notifications','settings.notificationsHelp':'Manage VPN and update notifications','settings.manageNotifications':'Manage Notifications',
  'license.title':'License','license.statusEmpty':'No serial validated','license.serial':'Serial number','license.account':'Account ID','license.validationUrl':'Validation URL','license.deviceLabel':'Device label','license.offlineGrace':'Offline grace token','license.offlineGraceHelp':'Use a signed grace window after online validation','license.activate':'Activate','license.validate':'Validate','license.clear':'Clear','license.allowed':'License allowed','license.denied':'License denied',
  'ai.title':'AI Engine','ai.statusEmpty':'Local fallback ready','ai.enable':'Enable AI Engine','ai.enableHelp':'Use external or local AI for anti-DPI tuning','ai.fallback':'Automatic local fallback','ai.fallbackHelp':'Fall back when APIs are blocked','ai.providerList':'Provider','ai.providerId':'Provider ID','ai.providerName':'Provider name','ai.providerType':'Provider type','ai.baseUrl':'Base URL','ai.endpoint':'Endpoint','ai.model':'Model','ai.apiAlias':'API key alias','ai.apiSecret':'API key / secret','ai.secretHint':'Leave empty to keep stored secret','ai.headers':'Headers JSON','ai.template':'Request template','ai.responsePath':'Response path','ai.saveProvider':'Save Provider','ai.testProvider':'Test',
  'updates.automatic':'Automatic Updates','updates.automaticHelp':'Check silently in the background','updates.current':'Current Version','updates.notChecked':'Not checked','updates.check':'Check for Updates','updates.download':'Download','updates.install':'Install','updates.checking':'Checking for updates','updates.upToDate':'Up to date','updates.available':'Update available','updates.ready':'Ready to install','updates.failed':'Update failed',
  'about.title':'About','about.original':'Integrated networking adapters','about.originalCredit':'Aether/MSN donor capabilities run only as internal adapters behind V2RayEZ Universal.','about.application':'Application: V2RayEZ GUI','about.applicationCredit':'V2RayEZ is the main application and preserved GUI; donor engines are integrated behind it.',
  'picker.empty':'No applications found','picker.added':'Executable added','picker.selected':'selected','toast.updated':'V2RayEZ is up to date','toast.telegram':'Telegram is unavailable; opened the browser.'
};

const fa = {
  'nav.about':'\u062f\u0631\u0628\u0627\u0631\u0647', 'connection.tap':'\u0628\u0631\u0627\u06cc \u0627\u0645\u0646\u06cc\u062a',
  'brand.subtitle':'شبکه خصوصی','nav.connect':'اتصال','nav.configurations':'پیکربندی‌ها','nav.settings':'تنظیمات',
  'actions.connect':'اتصال','actions.disconnect':'قطع اتصال','actions.reset':'بازنشانی پیش‌فرض‌ها','actions.apply':'اعمال','actions.selectAll':'انتخاب همه','actions.clearAll':'پاک کردن همه',
  'status.disconnected':'V2RayEZ Ready','status.connected':'V2RayEZ Active','status.connecting':'در حال اتصال…','status.disconnecting':'در حال قطع اتصال…','status.scanning':'در حال اسکن…','status.reconnecting':'در حال اتصال مجدد…','status.error':'خطای اتصال',
  'connection.ready':'برای محافظت از اتصال آماده است.','connection.connected':'','connection.connecting':'در حال آماده‌سازی مسیر امن.','connection.disconnecting':'در حال بازیابی شبکه.','connection.reconnecting':'در حال بازیابی مسیر امن.','connection.error':'V2RayEZ نیاز به بررسی دارد.',
  'traffic.upload':'ترافیک ارسالی','traffic.download':'ترافیک دریافتی','traffic.ping':'پینگ','traffic.locationUnavailable':'موقعیت در دسترس نیست','traffic.locationDetecting':'در حال تشخیص موقعیت…',
  'config.mode':'حالت اتصال','config.vpn':'VPN دستگاه','config.smart':'اتصال هوشمند','config.proxy':'پروکسی SOCKS5','config.protocol':'پروتکل','config.scan':'حالت اسکن','config.transport':'انتقال MASQUE','config.endpoint':'نقطه پایانی سفارشی','config.reconnect':'اتصال مجدد خودکار','config.reconnectHelp':'بازیابی پس از خطاهای موقت','config.dns':'مسیریابی خصوصی DNS','config.dnsHelp':'مسیریابی DNS از V2RayEZ','config.kill':'مسدودسازی هنگام خطا','config.killHelp':'مسدود کردن ترافیک هنگام بازیابی',
  'split.title':'تونل تفکیکی','split.help':'انتخاب کنید کدام برنامه‌ها از V2RayEZ استفاده کنند','split.include':'شامل برنامه‌ها','split.exclude':'مستثنا کردن برنامه‌ها','split.select':'انتخاب برنامه‌ها','split.search':'جست‌وجوی برنامه‌ها','split.add':'افزودن فایل اجرایی',
  'settings.appearance':'ظاهر','settings.system':'پیش‌فرض سیستم','settings.light':'روشن','settings.dark':'تیره','settings.language':'زبان','settings.notifications':'اعلان‌ها','settings.notificationsHelp':'مدیریت اعلان‌های VPN و به‌روزرسانی','settings.manageNotifications':'مدیریت اعلان‌ها',
  'license.title':'لایسنس','license.statusEmpty':'هیچ سریالی اعتبارسنجی نشده','license.serial':'شماره سریال','license.account':'شناسه حساب','license.validationUrl':'نشانی اعتبارسنجی','license.deviceLabel':'برچسب دستگاه','license.offlineGrace':'توکن مهلت آفلاین','license.offlineGraceHelp':'پس از اعتبارسنجی آنلاین از مهلت امضاشده استفاده شود','license.activate':'فعال‌سازی','license.validate':'اعتبارسنجی','license.clear':'پاک‌سازی','license.allowed':'لایسنس مجاز است','license.denied':'لایسنس رد شد',
  'ai.title':'موتور هوش مصنوعی','ai.statusEmpty':'جایگزین داخلی آماده است','ai.enable':'فعال‌سازی موتور هوش مصنوعی','ai.enableHelp':'استفاده از هوش مصنوعی بیرونی یا داخلی برای ضد DPI','ai.fallback':'جایگزین داخلی خودکار','ai.fallbackHelp':'وقتی APIها مسدود شدند به داخلی برگردد','ai.providerList':'ارائه‌دهنده','ai.providerId':'شناسه ارائه‌دهنده','ai.providerName':'نام ارائه‌دهنده','ai.providerType':'نوع ارائه‌دهنده','ai.baseUrl':'نشانی پایه','ai.endpoint':'اندپوینت','ai.model':'مدل','ai.apiAlias':'نام مستعار کلید API','ai.apiSecret':'کلید API / راز','ai.secretHint':'برای نگه‌داشتن راز ذخیره‌شده خالی بگذارید','ai.headers':'JSON هدرها','ai.template':'قالب درخواست','ai.responsePath':'مسیر پاسخ','ai.saveProvider':'ذخیره ارائه‌دهنده','ai.testProvider':'آزمایش',
  'updates.automatic':'به‌روزرسانی خودکار','updates.automaticHelp':'بررسی بی‌صدا در پس‌زمینه','updates.current':'نسخه فعلی','updates.notChecked':'بررسی نشده','updates.check':'بررسی به‌روزرسانی','updates.download':'دریافت','updates.install':'نصب','updates.checking':'در حال بررسی به‌روزرسانی','updates.upToDate':'به‌روز است','updates.available':'به‌روزرسانی موجود است','updates.ready':'آماده نصب','updates.failed':'به‌روزرسانی ناموفق بود',
  'about.title':'درباره','about.original':'آداپتورهای شبکه ادغام‌شده','about.originalCredit':'قابلیت‌های اهدایی Aether/MSN فقط به‌صورت آداپتور داخلی پشت V2RayEZ Universal اجرا می‌شوند.','about.application':'برنامه: V2RayEZ GUI','about.applicationCredit':'V2RayEZ برنامه و GUI اصلی است؛ موتورهای اهدایی پشت آن ادغام می‌شوند.',
  'picker.empty':'برنامه‌ای پیدا نشد','picker.added':'فایل اجرایی افزوده شد','picker.selected':'انتخاب‌شده','toast.updated':'V2RayEZ به‌روز است','toast.telegram':'تلگرام در دسترس نیست؛ مرورگر باز شد.'
};

export const translations = { en, fa };
let language = 'en';
export function t(key){return translations[language]?.[key]||translations.en[key]||key}
export function setLanguage(next){language=next==='fa'?'fa':'en';document.documentElement.lang=language;document.documentElement.dir=language==='fa'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(node=>node.textContent=t(node.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(node=>node.placeholder=t(node.dataset.i18nPlaceholder))}
export function applyTranslations(){setLanguage(language)}
export function currentLanguage(){return language}
